### ISSUE TITLE
A tag on this page requires an AMP component 'script' tag, which is missing.

### ISSUE THREAD

**Issue by DanielCryptoK** [ampproject/wg-stories#55]
Hi,

I am getting the following error for google amp stories.

An example page showing the error:

https://bitcoin-casino-no-deposit-bonus.com/bitstarz-promo-code/amp/

see attached
![AMP Test - Google Search Console](https://user-images.githubusercontent.com/45933242/100534677-1cf64a80-3244-11eb-98e6-929445cb8e73.png)

**Comment by gmajoulet** [comment]
Hello,

Is there anything that makes you think this is a bug? From [our documentation](https://amp.dev/documentation/components/amp-story-player/), you should load the Player JavaScript extension for it to work:
```
<script async custom-element="amp-story-player" src="https://cdn.ampproject.org/v0/amp-story-player-0.1.js"></script>
```

Feel free to reopen this ticket if I missed anything. Thanks!
