### ISSUE TITLE
Amp Story Cover Image Error

### ISSUE THREAD

**Issue by DanielCryptoK** [ampproject/wg-stories#56]
Hi,

I am trying to add a cover picture but keep on getting an error message. Can someone confirm if this feature is working correctly
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (13)](https://user-images.githubusercontent.com/45933242/102087411-17a41d00-3e4c-11eb-8058-fd53fded64df.png)
 along with the size in pixels that I need to upload.

**Comment by gmajoulet** [comment]
This is related to the WordPress plugin, can you re-open your issue on https://github.com/google/web-stories-wp please?
Thanks!
