### ISSUE TITLE
AMP Story sharing: Facebook AppId required

### ISSUE THREAD

**Issue by AutadeJS** [ampproject/wg-stories#6]
Why is Facebook AppId required to have it's sharing icon? If a website owner doesn't have AppId, they'll have to get one just to add the icon here?

**Comment by gmajoulet** [comment]
Hello,
It looks like the App ID is required for the Facebook share dialog: https://developers.facebook.com/docs/sharing/reference/share-dialog :(

**Comment by newmuis** [comment]
Closing this issue; as I believe @gmajoulet's response addresses the original question.  In the future, please use the https://github.com/ampproject/amphtml repository for filing issues and feature requests in the software; this repository is for managing the logistics of the @ampproject/wg-stories working group.
