### ISSUE TITLE
wg-stories Meeting Notes 2021-06-25

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/wg-stories#72]
# Updates to CTA

https://github.com/ampproject/amphtml/issues/34449

We’re developing a new system that unifies the CTA buttons at the bottom of the page, that can be configured with custom colors or icons, and allows users to swipe up or tap to open the attachment or link.

### Is it compatible with iOS 15?
We’re still thinking about this, and the tab bar currently covers the page attachments. There’s a few alternatives to consider, but we are working to have a solution before iOS 15 launches broadly.

### What will happen with the CTA layer?
We’ll deprecate the CTA layer in favor of this, and we’ll automatically convert CTA layer buttons to the new CTA UI. This will be deprecated after a long window in case creators want to update the page attachments to the new API.

### Can I have multiple CTAs on the page?
You can have multiple CTAs with the tooltip UI (anywhere on the page) that gives users two-click interactions. However, the one-click interaction is reserved for the page outlink at the bottom on the screen, which only allows 1 link / attachment. We can add multiple 1-click interactions on the bottom if needed for more specific scenarios, like multiple social media icons.

### When will this be released?
The new set of CTA APIs is already released and we’ll publish the documentation soon (there’s reference on). The CTA layer will be deprecated after a few months.

# Updates to desktop UI

https://github.com/ampproject/amphtml/issues/34479

We’re planning to restyle the desktop UI to use only 1 panel instead of 3. This is so that stories stay consistent between mobile and desktop, and the 3 panels desktop experience breaks the consistency in a few ways. Things like quizzes could have answers on the following pages, and showing panels for following pages could reveal the result. Animations or transitions between pages are also broken by the sliding animation on page transitions.

Also, the amp-story-player will be able to support next/prev story previews side by side. As more stories are seen in a Player, this UI will add a more immersive experience encouraging the consumption of more stories.

We will also be removing the viewport warnings! 🥳🥳

### How will supports-landscape be reflected in this UI?
Stories that support landscape will still take the full screen, even on players. The new UI is only changing desktop views, so on mobile, the UI will stay the same. We’ll start supporting mobile landscape as a result of this.

The UI to show more stories on the side is only configured by the amp-story-player API, and the player will only show the next/prev stories as configured in the list of stories provided on the Player.

### What page gets loaded on the stories?
The last page visited by the user is the page loaded, or the first page if the user is visiting that story for the first time.

### What’s up with the comments and likes seen in the mocks?
That mock shows what might be possible by websites extending the UI of the Player. Implementing these would require significant effort from the website, and (obviouslythe experiencece would be available when within that specific player. 

# General Q/A Section

### How does Core Web Vitals apply to stories? Eg: LCP
Context: web.dev/vitals
We’re working on improving the LCP which is typically the key challenge for Web Stories on CWV. There’s a list of improvements that we’re going through, and many of the improvements we’ve been shipping improve the UX but not necessarily CWV, which is why we’re currently talking with other performance teams at Google to improve the LCP. We’ve found multiple issues (like animations, auto-advance, etc) that we’ll be fixing short-term and long-term. 

We'll be publishing more detailed guidence around LCP soon as a blogpost, including a few things that tools/publishers can do to improve LCP (e.g. compress images properly etc.)

### What’s the future of paywalls in stories?
We’re going to work on this around Q4-Q1, and there’s multiple ways of doing this so we’ll share our design direction later in the year. 

### How can we use the half-half template on landscape without the text overlaying the image?
We haven’t seen a lot of stories use this template but we might be able to help better if we get an example story.

### Would you consider using iframes on stories?
In page attachments there are multiple valid experiences, but there’s UX and security implications so we’re moving cautiously. We don’t plan to allow iframes inside the story page though, maybe just on the attachments. We’d probably work on adding components to common use cases for iframes (eg: like what we’ve done with amp-twitter), but not allowing them directly on the pages.

### How can we have a read more and CTA button?
There’s no way to add two CTAs in the story, but you can add a two-click link anywhere on the story. Please add a feature request so we can check the use case and consider options if you need two CTAs.

### When will Stories be launched on Google apps in other countries?
We’re not in charge of the Google apps, we work on the components framework.

### Why can’t we use custom JS to show the ads?
We use amp-ads behind the scenes to ensure the performance and UX of ads. Please contact story-ads-wg@google.com to help with integration.

### How can I change the outlink of the results component depending on the answer? Happy to collaborate
We can help to review your feature request and consider alternatives / implementation details.

### How can I get a logged in user responses across many stories?
The client ID is consistent across all stories inside a same domain, so you’d only be able to do this if you:
- Control the stories inside that domain to know what are the options
- Own the backend to be able to match the responses to the stories (and get the correct/wrong value)
- Translate the base-64 URL passed to the backend to the raw URL of your story.
- Add a linker to your story to be able to share the clientID from the story onto your website, or have your website collect the client-ID for your domain
- Retrieve all the responses from the users on your website from your backend.
This is quite complex so we can answer any questions on this.

**Comment by jaygray0919** [comment]
*Would you consider using iframes on stories?*

>In page attachments there are multiple valid experiences, but there’s UX and security implications so we’re moving cautiously.
>We don’t plan to allow iframes inside the story page though, maybe just on the attachments.
>We’d probably work on adding components to common use cases for iframes (eg: like what we’ve done with amp-twitter), but not allowing them directly on the pages.

If we can't place an iframe on `amp-story-grid-layer` then iframe in `amp-story-page-attachment` is next best choice.
Currently we use iframe in non-valid amp-stories. Should we move those iframes to `amp-story-page-attachment` in anticipation of future validation?

Also, note the need we currently have (and use, even though non-valid): `amp-story-cta-layer` and `amp-story-page-attachment` for the same `amp-story-page`

**Comment by jaygray0919** [comment]
**amp-render**

Please consider supporting https://amp.dev/documentation/components/amp-render/

We would like to control an `amp-story-page` with content from `amp-render`.

**Comment by gmajoulet** [comment]
Supporting amp-render sounds good to me: https://github.com/ampproject/amphtml/issues/35185

**Comment by jaygray0919** [comment]
Can't use `amp-list` (more specifically `<template>`) as a parent of `amp-story-page`.
It only works as a child of each `amp-story-page` which leads to significant duplication of code/text.
The ideal is that `amp-story` is a child of `<template>`.
Then we would not have to repeat amp-list and template structure for each story-page.

While we have not tried it, `amp-render` probably has the same issue as it use `amp-mustache`

**Comment by gmajoulet** [comment]
The way we would implement it, `amp-render` would have the same issue for you as `amp-list`. Being able to dynamically render the entire content of `amp-story` and not just an `amp-story-page` poses a lot of new technical difficulties.

If that's what you need to do, I suggest you look into dynamically rendering your stories server side instead, and use your own rendering engine. There are an infinite number of ways to do it, I'm just linking to NextJS as an example https://nextjs.org/docs/api-reference/next/amp

**Comment by jaygray0919** [comment]
We have a compelling use-case for `<template>` control of all page content. We do this now for many conventional AMP pages. From our perspective, it's strange that there are different models for using `<template>` on **amp** pages. Further, using `<template>` we can control full page content when there is 1 or more `amp-story-players` on a single AMP page. Go figure.
