### ISSUE TITLE
wg-stories Meeting 2022-01-28

### ISSUE THREAD

**Issue by powerivq** [ampproject/wg-stories#94]
**Meeting date/time (UTC)**

2022-01-28 18:00

**Instructions for joining the meeting**

https://meet.google.com/mdz-axok-ndz?authuser=0&hs=122

**Agenda**
*Note: Add a comment on this issue to propose items for the agenda.*

**Comment by powerivq** [comment]
# Updates
## Shopping feature @ stories
Philip and Jonathan are primarily working on this feature since Q4 of 2021.

I2I: https://github.com/ampproject/amphtml/issues/36412

## Core web vital
AKA page experience. Stories have been having issues with LCP metrics. Stories are working on optimizing initial loading time.

## Story monetization
Experiment to auto advance stories to the next at ads. Confusing behavior when the content auto advances but the ads does not and is causing bounces.

A most robust ads placement algorithm: probabilistic approach to prevent shorter stories from never getting any ads.

## Subscriptions
An example would be paywall. Stories committed to do other monetization models, but want to ensure it is not too heavy weight. Feedbacks welcome.
 
## Forms
Swipe up to fill out any types of forms, e.g. email subscription. Feature already available, but documentation upcoming. Soliciting feedbacks.

## Automatic video captioning
Currently, we are able to add captions manually. Stories are looking to provide captions automatically for the publishers. Small audio playback stories improvement also in plan.

# Questions
## Shopping API detail
Philips describing in detail the shopping API design.

## Consent
Alex: Manage consent to track performance?

It is a publisher-centric question, but need to balance user experience. Stories wish too get more input.

## Search rollout
Gaetan: When web stories will be rolled out to Google in EU?

Stories working group is an open source initiative and only is focused on building the feature with all. The WG does not control Google search and the group is unable to predict that.

## CMS
Charlie: want to work with a consent management platform that works on the CMS.

**Comment by newmuis** [comment]
Thanks @powerivq!
